services:
  nhl-led-scoreboard:
    image: nhl-led-scoreboard-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=America/New_York
    ports:
      - 8888:8888
    volumes:
      - .:/app
