services:
  nhl-led-scoreboard:
    image: ghcr.io/falkyre/nhl-led-scoreboard:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=America/Winnipeg
    ports:
      - 8888:8888
    volumes:
      - './config/config.json:/app/config/config.json'
